name: Arch Linux

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --user root

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Refresh Packages
      run: pacman -Syu --noconfirm

    - name: Install Dependencies
      run: pacman -S --needed --noconfirm base-devel git extra-cmake-modules qt6-tools kwin

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j
