name: Fedora 40

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:40
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: dnf -y install git cmake extra-cmake-modules gcc-g++ kf6-kwindowsystem-devel plasma-workspace-devel libplasma-devel qt6-qtbase-private-devel qt6-qtbase-devel cmake kwin-devel extra-cmake-modules kwin-devel kf6-knotifications-devel kf6-kio-devel kf6-kcrash-devel kf6-ki18n-devel kf6-kguiaddons-devel libepoxy-devel kf6-kglobalaccel-devel kf6-kcmutils-devel kf6-kconfigwidgets-devel kf6-kdeclarative-devel kdecoration-devel kf6-kglobalaccel kf6-kdeclarative libplasma kf6-kio qt6-qtbase kf6-kguiaddons kf6-ki18n wayland-devel

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j
