name: Fedora 41

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: dnf -y install git cmake extra-cmake-modules gcc-g++ kf6-kwindowsystem-devel plasma-workspace-devel libplasma-devel qt6-qtbase-private-devel qt6-qtbase-devel kwin-devel kf6-ki18n-devel libepoxy-devel kf6-kcmutils-devel kdecoration-devel kf6-kdeclarative libplasma qt6-qtbase kf6-ki18n wayland-devel

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j
