name: KDE Neon (unstable)

on:
  push:
    branches: [ main, old ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main, old ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: invent-registry.kde.org/neon/docker-images/plasma:unstable
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Refresh Packages
        run: apt update

      - name: Upgrade Packages
        run: apt upgrade -y --allow-downgrades

      - name: Install Dependencies
        run: apt install -y cmake g++ extra-cmake-modules qt6-tools-dev kwin-dev libkf6configwidgets-dev gettext libkf6crash-dev libkf6globalaccel-dev libkf6kio-dev libkf6service-dev libkf6notifications-dev libkf6kcmutils-dev libkdecorations3-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j
