name: NixOS (Plasma 6.1.5)

on:
  push:
    branches: [ main, old ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main, old ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:33bca54e5e23eac33b668ebc71d576203f3ccf3b

    - name: Patch flake.nix
      run: sed -i 's/nixos-unstable/33bca54e5e23eac33b668ebc71d576203f3ccf3b/g' flake.nix

    - name: Update flake.lock
      run: nix flake update

    - name: Build
      run: nix build
