name: openSUSE Tumbleweed

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Refresh Packages
        run: zypper ref

      - name: Install Dependencies
        run: zypper in -y git cmake-full gcc-c++ kf6-extra-cmake-modules kcoreaddons-devel kwindowsystem-devel ki18n-devel kcmutils-devel "cmake(KF6CoreAddons)" "cmake(KF6GuiAddons)" "cmake(KF6I18n)" "cmake(KF6KCMUtils)" "cmake(KF6WindowSystem)" "cmake(Qt6DBus)" "cmake(Qt6Quick)" libepoxy-devel kwin6-devel

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j
